#!/usr/bin/env tsx
/**
 * Latency measurements for the voice-facing calls.
 *
 * The front end is a live conversation, so these numbers are a feature, not
 * trivia. Each call is measured cold (first call, caches empty) and then warm,
 * because the cold number is what the user feels on the first turn after a
 * restart and the warm number is what they feel for the rest of the session.
 */
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { buildApplication } from '../src/app.js';
import { createNullLogger } from '../src/logging/logger.js';
import { createHttpApp, startHttpServer } from '../src/server/http.js';

interface Measurement {
  name: string;
  coldMs: number;
  warmP50Ms: number;
  warmP95Ms: number;
  runs: number;
}

function percentile(sorted: number[], p: number): number {
  if (sorted.length === 0) return 0;
  const index = Math.min(sorted.length - 1, Math.floor((p / 100) * sorted.length));
  return sorted[index] ?? 0;
}

async function measure(name: string, fn: () => Promise<unknown>, runs = 20): Promise<Measurement> {
  const coldStart = performance.now();
  await fn();
  const coldMs = performance.now() - coldStart;

  const timings: number[] = [];
  for (let i = 0; i < runs; i += 1) {
    const start = performance.now();
    await fn();
    timings.push(performance.now() - start);
  }
  timings.sort((a, b) => a - b);
  return {
    name,
    coldMs,
    warmP50Ms: percentile(timings, 50),
    warmP95Ms: percentile(timings, 95),
    runs,
  };
}

async function main(): Promise<void> {
  // Benchmark against an isolated database. Sharing the live one both pollutes
  // real work-session history and contends with any running server, which
  // showed up here as a genuine SQLITE_BUSY.
  const workspace = mkdtempSync(join(tmpdir(), 'orchestrator-bench-'));
  const liveConfig = process.env['MCP_ORCHESTRATOR_CONFIG'] ?? 'config/orchestrator.yaml';
  writeFileSync(
    join(workspace, 'orchestrator.yaml'),
    [
      `# Generated by scripts/bench.ts; mirrors ${liveConfig} but with its own database.`,
      'server:',
      '  host: 127.0.0.1',
      '  port: 0',
      'database:',
      `  path: ${join(workspace, 'bench.sqlite')}`,
      'projects:',
      '  roots:',
      `    - ${process.cwd()}`,
      'logging:',
      '  level: error',
      '',
    ].join('\n'),
  );

  const app = await buildApplication({
    configPath: join(workspace, 'orchestrator.yaml'),
    cwd: workspace,
    logger: createNullLogger(),
  });
  const { services } = app;
  const results: Measurement[] = [];

  // Measure through the REAL MCP path, not the internal services, because the
  // tool layer adds caching and serialisation that the user actually feels.
  const { app: expressApp } = createHttpApp(services, { isReady: async () => ({ ready: true }) });
  const handle = await startHttpServer(expressApp, '127.0.0.1', 0, createNullLogger());
  const endpoint = `http://127.0.0.1:${handle.port}${services.config.server.mcpPath}`;
  const token = process.env[services.config.server.auth.tokenEnvVars[0] ?? ''] ?? '';
  let rpcId = 0;

  const callTool = async (name: string, args: Record<string, unknown> = {}): Promise<void> => {
    rpcId += 1;
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        accept: 'application/json, text/event-stream',
        ...(token ? { authorization: `Bearer ${token}` } : {}),
      },
      body: JSON.stringify({
        jsonrpc: '2.0',
        id: rpcId,
        method: 'tools/call',
        params: { name, arguments: args },
      }),
    });
    await response.text();
  };

  console.log('=== through the MCP tool layer (what the phone actually sees) ===\n');
  const toolResults: Measurement[] = [];
  toolResults.push(await measure('get_environment_context', () => callTool('get_environment_context'), 10));
  toolResults.push(await measure('list_context_capabilities', () => callTool('list_context_capabilities'), 10));
  toolResults.push(await measure('list_computers', () => callTool('list_computers'), 10));
  toolResults.push(await measure('find_project', () => callTool('find_project', { query: 'orchestrator' }), 10));
  toolResults.push(await measure('get_recent_activity', () => callTool('get_recent_activity'), 10));
  print(toolResults);

  console.log('\n=== internal services (uncached upper bound) ===\n');

  results.push(await measure('get_environment_context (default)', () => services.contextAssembler.assemble()));
  results.push(await measure('get_environment_context (coding)', () => services.contextAssembler.assemble({ profile: 'coding' })));
  results.push(await measure('get_environment_context (minimal)', () => services.contextAssembler.assemble({ profile: 'minimal' })));
  results.push(await measure('list_context_capabilities', () => services.contextAssembler.capabilities()));
  results.push(await measure('list_computers', () => services.computers.list()));
  results.push(await measure('get_computer (alias resolve)', () => services.computers.resolve('gpu')));
  results.push(await measure('list_projects', () => services.projects.list()));
  results.push(await measure('find_project', () => services.projects.resolve('orchestrator')));

  // Session status is a pure SQLite read; it must be effectively free.
  const session = services.sessionStore.create({
    instruction: 'bench session',
    mode: 'inspect',
    writeCapable: false,
  });
  services.sessionStore.setStatus(session.id, 'working', { summary: 'benching' });
  for (let i = 0; i < 40; i += 1) services.sessionStore.appendProgress(session.id, 'step', `step ${i}`);
  results.push(await measure('get_work_session_status', async () => services.sessions.getStatus(session.id), 50));
  results.push(await measure('get_recent_activity', async () => services.sessionStore.list({ limit: 10 }), 50));

  print(results);

  const slow = toolResults.filter((r) => r.warmP95Ms > 300);
  console.log(
    slow.length === 0
      ? '\nAll MCP-path warm p95 latencies are under 300ms.'
      : `\nSLOW MCP path (warm p95 > 300ms): ${slow.map((r) => r.name).join(', ')}`,
  );

  await handle.close();
  await app.shutdown();
  rmSync(workspace, { recursive: true, force: true });
}

function print(results: Measurement[]): void {
  const pad = Math.max(...results.map((r) => r.name.length));
  console.log(`${'call'.padEnd(pad)}  ${'cold'.padStart(9)}  ${'warm p50'.padStart(9)}  ${'warm p95'.padStart(9)}`);
  console.log('-'.repeat(pad + 33));
  for (const result of results) {
    console.log(
      `${result.name.padEnd(pad)}  ${result.coldMs.toFixed(1).padStart(7)}ms  ${result.warmP50Ms
        .toFixed(1)
        .padStart(7)}ms  ${result.warmP95Ms.toFixed(1).padStart(7)}ms`,
    );
  }
}

main().catch((error: unknown) => {
  console.error('bench failed:', error);
  process.exit(1);
});
